import type { Metadata } from "next";
import { Inter, Poppins, Tilt_Neon } from "next/font/google";
import HeaderComponent from "./components/header";
import LiComponent from "./components/header/li";
import { homeRef } from "./lib/utils";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const tilt_neon = Tilt_Neon({ subsets: ["latin"], variable: "--font-tilt" });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      {/* max-md:hidden */}
      <body className={`${poppins.className} grid justify-items-center `}>
        <HeaderComponent add={"max-md:hidden"}>
          {homeRef.map((ref) => {
            return <LiComponent name={ref.name} idRef={ref.idRef} />;
          })}
        </HeaderComponent>

        {children}

        <HeaderComponent add={"border-red-500 border md:hidden"}>
          {homeRef.map((ref) => {
            return <LiComponent name={ref.name} idRef={ref.idRef} />;
          })}
        </HeaderComponent>
      </body>
    </html>
  );
}
